kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp2"
  volumeMode: Filesystem
  hostPath:
    path: /tmp/{{ .Release.Name }}-pv
    type: ''
  claimRef:
    name: {{ .Release.Name }}-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: "gp2"
  volumeName: {{ .Release.Name }}-pv