kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pv
spec:
  capacity:
    storage: 200Mi
  mountOptions:
    - hard
    - nfsvers=4.0
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  volumeMode: Filesystem
  hostPath:
    path: /tmp/{{ .Release.Name }}-pv
    type: ''
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: gp2    